version: '3.8'

services:
  backend:
    image: ashish7763/codeash-backend
    build: ./Backend

    env_file:
      - ./Backend/.env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: ashish7763/codeash-frontend
    build:
      context: ./Frontend
      args:
        VITE_API_BASE_URL: http://43.204.227.122:3000

    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
