version: '3.8'

services:
  backend:
    build: ./Backend
    ports:
      - '3000:3000'
    env_file:
      - ./Backend/.env
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_API_BASE_URL: http://localhost:3000
    ports:
      - '5173:80'
    networks:
      - app-network
    restart: unless-stopped
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
